### ISSUE TITLE
jdomino

### ISSUE THREAD

**Issue by zvezdochiot** [u-235/Nu-Pogody#1]
Hi @u-235 .

Прошу помощи в поддержке https://github.com/World-of-Domino/jdomino . Java не мой конёк.

**Comment by u-235** [comment]
Привет. Я не совсем понимаю что нужно делать. Нет ни issue с проблемами, ни TODO с идеями по развитию.

**Comment by zvezdochiot** [comment]
Hi @u-235 .

Ну да нету. Но если возникнут, то мне и ответить будет нечем. Я даже скомпилить и отдебаждить не смогу. Ежели за-invoke-ть тебя в организацию, вступишь?

**Comment by u-235** [comment]
> Ежели за-invoke-ть тебя в организацию, вступишь?

Это что-то вроде сопровождения проекта? Надо подумать.

**Comment by zvezdochiot** [comment]
Hi @u-235 .

Нет. Это возможность вносить правки в код без форков и PR. Своего рода общие репозитории. Гораздо удобнее и в плане времени и в плане git-истории (проверено на практике).

PS: Invoke отправляю. Ничего "сверхестественного" не ожидаю. Просто не устраивает меня "единоличный" доступ к репе. Думай.

**Comment by u-235** [comment]
С другой стороны, почему бы и нет.
